name: Build

env:
  PYTHON_VERSION: '3.10'

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Install cx_Freeze
        run: pip install cx_Freeze
      - name: Build Native Executable
        run: python setup.py build
      - name: Get commit hash
        id: commit
        uses: pr-mpt/actions-commit-hash@v1
      - name: Upload Compiled Version
        uses: actions/upload-artifact@v3
        with:
          name: VALORANT-rank-yoinker-${{ steps.commit.outputs.short }}
          path: build/exe.win-amd64-${{ env.PYTHON_VERSION }}/**
